### ISSUE TITLE
Universal Analytics

### ISSUE THREAD

**Issue by jrglasgow** [GSA/DAP-Gov-wide-GA-Code#1]
Is there a plan for GSA to update this code to use Google's new Universal Analytics? If so where can I find information about the process?

**Comment by konklone** [comment]
This looks closeable, right? There's ample information on the DAP's DigitalGov home, in this repository, and in #2.

**Comment by tdlowden** [comment]
Hi JR. Apologies for the delay here. The UA code is currently in this repo and we will be formally asking agencies to begin updating next week. We'll also have some office hours sessions for people to call in with questions. I see you aren't a federal employee, but the information will be distributed through our user listserv.

**Comment by jrglasgow** [comment]
FYI I am currently maintaining this Drupal module https://www.drupal.org/project/usfedgov_google_analytics which puts the analytics code on a Drupal site. I have updated it for DHS to use your analytics script. I believe that I have it working properly but as I have not seen any documentation nor do I have access to one of the accounts to make sure it is working.

This update of the module to use the universal analytics will begin to be deployed by DHS properties later this month.
