### ISSUE TITLE
Centrally hosted snippet should drop version number

### ISSUE THREAD

**Issue by konklone** [GSA/DAP-Gov-wide-GA-Code#14]
The current "in testing" version of the DAP snippet has the version number in the URL:

> https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.1.0.js

It looks like this has stayed static as the snippet's internal version numbering system has moved from `1.0.2` to `1.0.3`, etc. I'm not sure if the DAP intends to update the filename if the version is increased to `1.1` or `2.0`.

But the much simpler thing is to drop the version number entirely. As it is, if the DAP ever does increase the version number, renaming the file will require the DAP to go around and ask every participating site to update their snippet again -- which is the dynamic that centrally hosting the snippet is intended to prevent. 

In practice, the DAP could just ignore the filename and never update it, even if the internal version numbering increases to `2.0`, but in that case, why have it in the filename at all anyway?

I understand the snippet hosting configuration is set up to pull directly from GitHub, so this likely means renaming the file in GitHub as well.

**Comment by tdlowden** [comment]
We've renamed the file and dropped the version number :)

**Comment by konklone** [comment]
Nice! :+1:
