### ISSUE TITLE
which file to use?

### ISSUE THREAD

**Issue by aaronsnow** [GSA/DAP-Gov-wide-GA-Code#2]
It's somewhat unclear which of these files we're supposed to use. Could someone in-the-know indicate in the README which one to use, or what the diffs are between these files so we know how to choose? Thanks ...

**Comment by konklone** [comment]
@tdlowden told me at one point that it was this one, and it is in fact the most recently updated version:

https://github.com/GSA/DAP-Gov-wide-GA-Code/blob/master/Universal-Federated-Analytics.1.0.js

If it's helpful, I've got versions of this file here:

* https://analytics.usa.gov/dap/dap.js - original
* https://analytics.usa.gov/dap/dap.min.js - minified
* https://analytics.usa.gov/dap/dap.min.js.map - source map from minified to original

All 3 are compressed via gzip, stored in S3, and served by CloudFront. We're using it to have the https://analytics.usa.gov dashboard itself report to the DAP.

**Comment by tdlowden** [comment]
Eric is right and pointed out the correct file. I'll see if I can make it easier to distinguish.
