### ISSUE TITLE
Remove eduardocereto@gmail.com from all sources

### ISSUE THREAD

**Issue by eduardocereto** [GSA/DAP-Gov-wide-GA-Code#4]
Can you guys please remove my personal email from the source code?

eduardocereto@gmail.com

This has been generating a lot of spam. 

You can leave or remove my name, I don't mind. I just ask you to remove the email address.

**Comment by tdlowden** [comment]
Resolved

**Comment by BaseMax** [comment]
> Can you guys please remove my personal email from the source code?
> 
> This has been generating a lot of spam.

Hey, @eduardocereto @tdlowden  

I suggest to rename the title of this issue or remove the email address from the title., Thanks,

Regards,
Max
