### ISSUE TITLE
Turn "Force SSL" flag on by default in the DAP

### ISSUE THREAD

**Issue by konklone** [GSA/DAP-Gov-wide-GA-Code#8]
The DAP snippet version 1.01 currently doesn't enable the [Force SSL](https://developers.google.com/analytics/devguides/collection/analyticsjs/advanced#ssl) flag:

https://github.com/GSA/DAP-Gov-wide-GA-Code/blob/bf42c494aa0af5f68ea2cb0c3b0c187a40e4a762/Universal-Federated-Analytics.1.0.js#L46

Turning on the flag means that even http:// websites will talk to Google Analytics over https://. This increases visitor privacy for users visiting DAP-enabled websites. Without it, visitor information will be sent in plain text over the network for any .gov site that doesn't use HTTPS (which, sadly, is still many of them).

There's no downside -- this flag won't break anything, and in fact, Google should really just turn it on for everyone and remove the option. The only reason it exists is because of the [now-deprecated](http://www.paulirish.com/2010/the-protocol-relative-url/) idea that you may as well use http:// assets on http:// pages to save on speed.

Because the DAP is about to have a public footprint, and this is a visitor privacy issue, I suggest this change be prioritized.

**Comment by tdlowden** [comment]
Appreciated! Implemented into latest code
