### ISSUE TITLE
WH Petitions Data coming up with invalid URLs

### ISSUE THREAD

**Issue by konklone** [GSA/DAP-Gov-wide-GA-Code#9]
White House petitions URLs are coming up with these slugs at the end:

![screenshot from 2015-03-08 15 25 57](https://cloud.githubusercontent.com/assets/4592/6547191/71f13672-c5a7-11e4-9901-d3a47583ed63.png)

This leads to URLs like this:

> https://petitions.whitehouse.gov/petition/take-out-alejandro-garc%C3%ADa-padilla-governorship-puerto-rico-now/b0jgb8sv

Which are not valid when visited. I can't tell why this is the case. It's breaking links over at the DAP dashboard, and I guess we could hardcode some fixes for them, but I'd much rather understand why.

cc @lheyman

**Comment by lheyman** [comment]
The slugs are supposed to be there (long story), but are case sensitive, and for some reason it looks like they're getting down-cased here.
For example, here is the valid URL for the link you posted:
https://petitions.whitehouse.gov/petition/take-out-alejandro-garc%C3%ADa-padilla-governorship-puerto-rico-now/B0jgB8Sv

**Comment by konklone** [comment]
Thank you, @lheyman, I understand the root cause better now. Closed in favor of #10.
